apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy